set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

SET(COMPILER_PATH /mnt/c/Users/ermac/Documents/wsl/gcc-arm-none-eabi-9-2019-q4-major)
SET(COMPILER_BIN ${COMPILER_PATH}/bin)
SET(TOOLCHAIN_LIBC_DIR ${COMPILER_PATH}/arm-none-eabi)
SET(TOOLCHAIN_INC_DIR ${TOOLCHAIN_LIBC_DIR}/include)
SET(TOOLCHAIN_LIB_DIR ${TOOLCHAIN_LIBC_DIR}/lib)

SET(COMPILER_PREFIX arm-none-eabi-)

SET(CMAKE_C_COMPILER "${COMPILER_BIN}/${COMPILER_PREFIX}gcc" CACHE INTERNAL "")
SET(CMAKE_ASM_COMPILER "${COMPILER_BIN}/${COMPILER_PREFIX}gcc" CACHE INTERNAL "")
SET(CMAKE_CXX_COMPILER "${COMPILER_BIN}/${COMPILER_PREFIX}g++" CACHE INTERNAL "")
SET(CMAKE_OBJCOPY "${COMPILER_BIN}/${COMPILER_PREFIX}objcopy" CACHE INTERNAL "")
SET(CMAKE_SIZE "${COMPILER_BIN}/${COMPILER_PREFIX}size" CACHE INTERNAL "")
SET(CMAKE_OBJDUMP "${COMPILER_BIN}/${COMPILER_PREFIX}objdump" CACHE INTERNAL "")
SET(CMAKE_CMAKE_LINKER "${COMPILER_BIN}/${COMPILER_PREFIX}ld" CACHE INTERNAL "")


SET(CMAKE_C_FLAGS "-isystem ${TOOLCHAIN_INC_DIR} -std=gnu99" CACHE INTERNAL "c compiler flags")
SET(CMAKE_CXX_FLAGS "-isystem ${TOOLCHAIN_INC_DIR}" CACHE INTERNAL "cxx compiler flags")

set(CMAKE_EXE_LINKER_FLAGS "--specs=nosys.specs" CACHE INTERNAL "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)